[Interface]
PrivateKey = QP3V0mdX27IzHvNsxtbYK1Oqy8SP6LHUTfDZT55VTnA=
Address = 198.51.100.2/32

[Peer]
PublicKey = wXr9onvGJKFY8IPQ4o8tFL3lRq6RPILUBFVWZQZi83M=
Endpoint = 34.24.211.107:51820
AllowedIPs = 198.51.100.1/32,10.1.0.0/16
PersistentKeepalive = 25
